### ISSUE TITLE
DHC: Update icons for core values 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#101]
http://fontawesome.io/icons/

Scholarship: university
Comprehensiveness: pie-chart
Connectedness: connectdevelop
Collaboration: handshake-o
Sustainability: life-ring

**Comment by waynegraham** [comment]
This is mostly fixed (but https://github.com/clirdlf/clir_theme/issues/102)

**Comment by nkferraiolo** [comment]
We'll also need to add a symbol for the core value of openness. How about spinner? 
http://fontawesome.io/icons/

**Comment by waynegraham** [comment]
the `handshake-o` is from the 4.7.0 icons and we have 4.3.0. In the update there is something weird going on and for right now there's not enough time to get in to this. I updated the `handshake-o` to use the `fa-users` icon and added `fa-retweet` for the **Openness** header.
