### ISSUE TITLE
DHC: How to make text more visible on slider images

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#106]
Wayne, 

Do you have any suggestions for how to make the text more visible on the slider images? I was thinking about adding a solid band of color behind the text like you did with the first CLIR landing-page mock-up, but I can't figure out how to do it in slider revolution. Do you have any suggestions? 

Thanks!

Nikki

**Comment by waynegraham** [comment]
Did I answer this question this morning with the background shape?

**Comment by nkferraiolo** [comment]
Yes I think so, but let’s leave this thread open, so I remember to apply it to the other pages!

**Comment by waynegraham** [comment]
With updated knowledge, the way you were doing this is probably way better. The trick is just to adjust the line height (on the initial edit view) to be larger than the font size (e.g. 48px font with a 5px border is 58px).
