### ISSUE TITLE
Re-link new home page to Home on top navigation bar

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#108]
Clicking on Home at the top takes you to https://staging.clir.org/welcome/

**Comment by waynegraham** [comment]
Do we need that nav element? The logo in the left goes to the main home (as does the title bar)

**Comment by Katsmi60** [comment]
We probably don’t need that element. Is there a best practice for that?

**Comment by waynegraham** [comment]
Let's drop this navigation then (see https://www.webdesignerdepot.com/2015/08/the-ux-case-against-the-home-button/). There aren't "best practices" per se on this, but I ascribe to the following guidelines:

- Prioritize consistency
- Design clear interactions
- Avoid deep navigation
- Design for responsive compatibility

See http://www.uxbooth.com/articles/the-rules-for-modern-navigation/ for more on this.
