### ISSUE TITLE
Try this for recurring child page banner?

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#111]
I've reduced the opacity of this version, but don't know if it will look too washed-out and uninteresting. Can we try? It's sized bigger vertically than it needs to be-- crop as necessary.
![mosaic-2-small-light](https://user-images.githubusercontent.com/25488670/31513118-314afe00-af5b-11e7-8517-083684f88415.png)

**Comment by Katsmi60** [comment]
Didn't want to wash it out too much, but maybe it's still too dark for good contrast with lettering... let me know what you think. I can take it back further.'

**Comment by waynegraham** [comment]
This is set in **Appearance > Customize > Page Title Bar > Page Titlebar Options**

We may need to darken this a bit more with a mask.

**Comment by Katsmi60** [comment]
Is the image you used the one with opacity? It looks more vibrant than the one I pushed back. What happens if we use black lettering?

**Comment by waynegraham** [comment]
It was the one uploaded; the major problem I see with this is that we can't control the gamma on people's monitors and will wash out a lot of text. We can look at changing that text to a dark gray instead, but we still may have some problems.
