### ISSUE TITLE
Make sponsor/funder list two columns?

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#131]
Is there a way to make the long sponsor/funder list at https://staging.clir.org/about/current-sponsors-and-funders/

two columns? Also, in several places, the symbol that should follow the name appears on the next line as a bullet.

**Comment by LouisaKwasigroch** [comment]
Should be able to split between Pacific Lutheran & Penn State if I counted right (103/103 = 206 total institutions).

I was able to fix the bullets/symbols and deleted the extra institutions.
