### ISSUE TITLE
Logos too big on affiliates page

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#132]
Wayne, I'm not sure whether you still want us to submit tickets, or if you'd prefer to have feedback in another way. Just let me know. In the meantime, I'm going to create a few tickets for things that seem to still need attention.

The iiif and NDSA logos on the affiliates page are too big and should be made consistent in size with the others.

**Comment by waynegraham** [comment]
I made them all the same width, but because IIIF is a square logo, it still appears quite a bit larger than the other logos

https://staging.clir.org/initiatives-partnerships/clir-affiliates/
