### ISSUE TITLE
RaR news item needs to link to most recent press release

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#135]
How do I link the RaR news item to the most recent news release? It currently links to the April release.

**Comment by waynegraham** [comment]
On the post, set a featured image (bottom right in the edit view)

**Comment by Katsmi60** [comment]
I did set the featured image for the new RaR award news release, but the is not showing up on the home page. Is there an extra step I need to take for that?

Kathlin

**Comment by waynegraham** [comment]
This was fixed last week
