### ISSUE TITLE
Staff page layout

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#137]
Is layout treatment for Lizzi the model intended for use for the rest of the page? Photo seems too large, and arrangement seems to be created for mobile device rather than wide screen (viewed on wide screen, there's a lot of scrolling down and wasted horizontal space.

**Comment by waynegraham** [comment]
Staff have been brought in to a new Team plugin with a default layout.

https://staging.clir.org/about/staff/
