### ISSUE TITLE
Other Resources under CLIR Publications needs to be fixed

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#142]
It currently links to Hidden Collections

**Comment by waynegraham** [comment]
To be clear, is this the menu (which appears to be correct) or a link on some other page?

**Comment by Katsmi60** [comment]
Hi, Wayne,

The problem is at https://staging.clir.org/pubs/

On that page, the link to Other Resources is incorrect.

The page that is reached from the dropdown menu https://staging.clir.org/pubs/resources/ is correct.

Thanks,

Kathlin

**Comment by waynegraham** [comment]
Fixed
