### ISSUE TITLE
Embedded Giving Form Not Working

### ISSUE THREAD

**Issue by LouisaKwasigroch** [clirdlf/clir_theme#145]
https://staging.clir.org/give/

Code from Qgiv:

<div class="qgiv-embed-container" data-qgiv-embed="true" data-embed-id="49508" data-embed="https://secure.qgiv.com/for/colair/embed/49508/" data-width="564"></div>
<script>(function(w, d, s, id){var js, fjs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) return;js = d.createElement(s); js.id = id;js.src = "https://secure.qgiv.com/resources/core/js/embed.js";fjs.parentNode.insertBefore(js, fjs);})(window, document, 'script', 'qgiv-embedjs');</script>

**Comment by LouisaKwasigroch** [comment]
https://support.qgiv.com/hc/en-us/articles/204624374-Widgets-Qgiv?flash_digest=de9cb15266cd7c861e1c1ab987d31ab971283407

**Comment by waynegraham** [comment]
The document you linked to is behind a login; is there a way to set up an account for me?

**Comment by waynegraham** [comment]
I added this snip as a shortcut, which is embedding the JavaScript call to the `embed.js` file

**Comment by LouisaKwasigroch** [comment]
I did add you already--probably in SPAM?

**Comment by LouisaKwasigroch** [comment]
Once you are in, here's the actual page to make the widget: https://secure.qgiv.com/control/widgets/ -- right now I only have one form CLIR Standard, so that's the one I want to embed.

**Comment by LouisaKwasigroch** [comment]
Okay, maybe I had a weird link in there -- can we try this:

<div class="qgiv-embed-container" data-qgiv-embed="true" data-embed-id="49508" data-embed="https://secure.qgiv.com/for/colair/embed/49508/" data-width="564"></div>
<script>(function(w, d, s, id){var js, fjs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) return;js = d.createElement(s); js.id = id;js.src = "https://secure.qgiv.com/resources/core/js/embed.js";fjs.parentNode.insertBefore(js, fjs);})(window, document, 'script', 'qgiv-embedjs');</script>

**Comment by waynegraham** [comment]
There was a bit more in the embed code; this is fixed now.
