### ISSUE TITLE
Issue with H3 bold turning burgundy also seen at https://staging.clir.org/about/clir-brandmark/

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#149]
It seems that the style designation for H3 bold is burgundy on some pages, and black on others. Would like to have it be uniformly black.

**Comment by waynegraham** [comment]
This seems to be from the copy-n-paste from the current site; are there other pages you've seen this on?

**Comment by waynegraham** [comment]
Actually, these have a header and the `<strong>` (e.g. <h3><strong>header</strong></h3>`. These need to be cleaned up

**Comment by waynegraham** [comment]
I've cleaned these up.
