### ISSUE TITLE
CLIRgive, Qgiv form no longer working https://staging.clir.org/give/

### ISSUE THREAD

**Issue by LouisaKwasigroch** [clirdlf/clir_theme#152]
<div class="qgiv-embed-container" data-qgiv-embed="true" data-embed-id="49508" data-embed="https://secure.qgiv.com/for/clir/embed/49508/" data-width="564"></div>
<script>(function(w, d, s, id){var js, fjs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) return;js = d.createElement(s); js.id = id;js.src = "https://secure.qgiv.com/resources/core/js/embed.js";fjs.parentNode.insertBefore(js, fjs);})(window, document, 'script', 'qgiv-embedjs');</script>

I know we'll have to update it once it isn't on "staging" anymore, just hoping we can get it to work again.

**Comment by waynegraham** [comment]
This script also needs a dom element to attach to:

```
<div class="qgiv-embed-container" data-qgiv-embed="true" data-embed-id="49508" data-embed="https://secure.qgiv.com/for/clir/embed/49508/" data-width="564"></div>
<script>(function(w, d, s, id){var js, fjs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) return;js = d.createElement(s); js.id = id;js.src = "https://secure.qgiv.com/resources/core/js/embed.js";fjs.parentNode.insertBefore(js, fjs);})(window, document, 'script', 'qgiv-embedjs');</script>
```
