### ISSUE TITLE
Staff page shows double set -- staff are also appearing under Presidential Fellows

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#153]

**Comment by waynegraham** [comment]
I have a ticket into the plugin developer for this. If this is not resolved by next week, I'll manually fix this with HTML until it can be resolved.

**Comment by waynegraham** [comment]
Just and update on this. I worked with the developer of the codebase and he's written a patch that he is in the process of deploying through the WordPress plugin repository. I've tested the fix locally and it does resolve this issue. The actual fix for this will be put in place when the `wp_cron` runs to check for updates. I'll leave this ticket open until that plugin update has been propogated.
