### ISSUE TITLE
DHC: Subtext below timeline items 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#161]
Is it possible to include a space for subtext below each timeline item in the key dates section on the DHC landing page? I think the original code included a space for this but I can't figure out how to add it now.

**Comment by nkferraiolo** [comment]
When using Heading 3, some of the text is burgundy and some is black. What's going on here? Is it a matter of whether it's in bold or unbold? Is there a way to make the text bold and black?

**Comment by waynegraham** [comment]
You have `<h3><strong>text</strong></h3>`. To remove the burgundy, click on the **b** icon in the editor.
