### ISSUE TITLE
DHC: Resize core values image to better fit the space 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#163]
This image seems to work differently than the other ones. I'd love some help resizing it to better fit the space.

**Comment by waynegraham** [comment]
You're not really going to be able to get an image that fits the full height of this on every browser size. I went in and adding more padding at the top to fit it more in the center of the section. 

Is there something else you're wanting to do?

**Comment by nkferraiolo** [comment]
That makes sense. In that case this is fine. Thanks!
