### ISSUE TITLE
DHC + MF: Missing navigation bars 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#181]
I tried to put in the left-hand navigation bars using the code provided over slack. 

[ms_section contents_in_container=“yes” id=“about”]
[ms_column style=“1/3” align=“left” class=“” id=“”]
[listmenu menu=“Digitizing Hidden Collections” container_id=“program_menu” ]
[/ms_column]
[ms_column style=“2/3” align=“left” class=“” id=“”]
[/ms_column] 

Unfortunately it didn't work and came out looking like this: 

![screenshot 2017-11-26 19 06 10](https://user-images.githubusercontent.com/17573921/33246700-b2991250-d2e5-11e7-9746-f47cea1f6aa1.png)

Wayne, might you be able to help with this? I believe that the DHC Program History page is the only one still missing the left-hand nav bar.

**Comment by waynegraham** [comment]
Is this for both hidden collections and mellon? Could you include the URLs?

**Comment by waynegraham** [comment]
If found this, and it looks like it's the fault of "smart" quotes (e.g. “ vs ").
