### ISSUE TITLE
MF: Partially-sucessful attempt to replicate part of DHC For Applicants page

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#182]
I tried to replicate the Document Library section of the DHC Applicant Resources page on the MF Recipient Resources page. It was mostly successful, but I can't figure out how to get the grey background to show up in the entire section. Currently, it's just a grey bar at the top. Can you help with this?

**Comment by waynegraham** [comment]
Can I get a URL?

**Comment by waynegraham** [comment]
There were nested (unclosed) sections causing this.
