### ISSUE TITLE
IMPORTANT: Temporary guidelines until Jan 2018 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#187]
Where can I find the equivalent of this page on the new site? 
https://www.clir.org/hiddencollections/applicants/applicantguidelines.html

We'll need to link to it from the applicants resources page guidelines feature box until the new guidelines are ready in mid January 2018. 
https://staging.clir.org/hiddencollections/applicant-resources/#

**Comment by waynegraham** [comment]
https://staging.clir.org/hiddencollections/applicationguidelines/
