### ISSUE TITLE
broken RSS link in footer

### ISSUE THREAD

**Issue by nowviskie** [clirdlf/clir_theme#192]
Minor issue, but I can't figure out how/where to adjust the Social Media links in the footer widget and that one is broken. (It seems like the "Customize" options I was relying on heavily this weekend are now gone... Maybe that was there?)

**Comment by waynegraham** [comment]
This is due to the editor having links to the site https://demomageewp.com, but their cert has expired. I can't fix this, but I'll write a rewrite rule to get around this until they fix it.

**Comment by waynegraham** [comment]
The cert issue got resolved. I went in and changed this to /feed

**Comment by nowviskie** [comment]
Thank you!
