### ISSUE TITLE
IMPORTANT: MF Guidelines 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#193]
Where is the equivalent to this link on the new website? 
https://www.clir.org/fellowships/mellon/applicants.html/applicantguidelines.html

**Comment by waynegraham** [comment]
https://staging.clir.org/fellowships/mellon/applicantguidelines/

**Comment by nkferraiolo** [comment]
These appear to be the 2016 guidelines for the MF program. Do you know where the 2017 guidelines are? Depending on when the site was migrated, they may have not been moved over.

**Comment by waynegraham** [comment]
Easiest thing to do is copy-n-paste the new stuff at this point

**Comment by nkferraiolo** [comment]
OK will do. Thx.
