### ISSUE TITLE
broken image links in blog posts

### ISSUE THREAD

**Issue by nowviskie** [clirdlf/clir_theme#194]
a programmatic fix would be welcome for cases like this in the DLF blog:

https://staging.diglib.org/archives/11187/

Something to do with the `image_frame` shortcode? 

Scroll down a bit in this category list and you'll see a bunch of them with the problem, spring 2016 and earlier: https://staging.diglib.org/contribute/

**Comment by waynegraham** [comment]
https://staging.diglib.org/archives/7352/

[image_frame style=”framed_shadow” alt=”Dale Askey” title=”Dale Askey” height=”100″ width=”100″ caption=”Dale Askey”]http://dlf-staging.wordpress.clir.org/wp-content/uploads/sites/5/2014/12/askey-dale-square.jpg[/image_frame]

**Comment by waynegraham** [comment]
Moving to https://github.com/clirdlf/clir-widgets-bundle/issues/14
