### ISSUE TITLE
IMPORTANT DHC: Missing subpages 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#195]
We used to have separate pages with information for the CHC and DHC reporting requirements. I thought I had tested these links yesterday, but apparently did not. Can you help me migrate this information over. This is very important. 

We link to them on these pages. If we still have access to the original site somewhere, I can find those pages for you. It's important to access them because I don't have the text saved anywhere.

**Comment by waynegraham** [comment]
Can I get some links for what page to look at and what pages are missing?

**Comment by nkferraiolo** [comment]
https://www.clir.org/hiddencollections/recipients/cataloging-hidden-collections-reports
https://www.clir.org/hiddencollections/recipients/digitizing-hidden-collections-reports

Here are the links of the missing pages. They currently direct to oops pages. If there's a place I can access the old site, I can find them for you there.

**Comment by waynegraham** [comment]
These weren't on the staging site so I moved them from http://cms.clir.org. Links to documents should be good to go (https://www.clir.org/hiddencollections/recipients/cataloging-hidden-collections-reports
https://www.clir.org/hiddencollections/recipients/digitizing-hidden-collections-reports). I'm not sure what pages link in to those pages, but could you verify?

**Comment by nkferraiolo** [comment]
These are the correct links. Thanks so much, Wayne!
