### ISSUE TITLE
URGENT: Redirect old links 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#217]
Kristen just discovered that with the changed names of the subpages for the DHC website section (and likely MF and RAR sections), new URLs have been created. When people use the old URLs, they are taken to automatically-skinned pages on the new website, but which have dated, unformatted content. Can you help make sure that these old pages redirect to the correct pages? I can let you know which ones should go where. It'll take some time to track them all down, but for starters, here's the one we discovered this morning. This is important because the old links were used in many previous communications that people may still be referencing. 

Old link: https://www.clir.org/hiddencollections/recipients/recipients/
Should redirect here: https://www.clir.org/hiddencollections/recipient-resources/

Thank you!!

**Comment by waynegraham** [comment]
The way the redirects work right now is if there is a link with `.html`, it's redirected to the same path without the `.html` extension. 

There is a tool in Wordpress (under Tools -> Redirection) to set permanent redirects (301s). I've been logging the 404s to try to find patterns to take care of large groups of these. However,  if you find any of these, feel free to add them in with the pattern you see on the other entries.

**Comment by nkferraiolo** [comment]
Thank you for letting me know how this works. I would prefer if you could take care of it this time, since this is time sensitive and I don't have time to learn a new skill at the moment. This task feels out of scope for the work that was requested of program staff (i.e. to provide content and design guidance) at the onset of this project, which we have all done, plus much of the design implementation (which I did not expect to have to do when I first agreed to help with this project). I do not think it should be program's staff responsibility to do backend work on the website as well, especially because we have been given no training in this area and there is a significant amount of wasted time that is spent trying to teach ourselves how to use the new system, since the work we have been asked to do extends beyond the tutorials provided to us. 

Thank you for understanding.

**Comment by waynegraham** [comment]
Github issues isn't really the place for this, but if you would like to talk more, I'm more than willing to discuss with you.

**Comment by nkferraiolo** [comment]
Here are some of the other links that need to be permanently redirected ASAP: 

**DHC:**
Old link: https://www.clir.org/hiddencollections/applicants/
New link: https://www.clir.org/hiddencollections/applicant-resources/

Old link: https://www.clir.org/hiddencollections/recipients/
New link: https://www.clir.org/hiddencollections/recipient-resources/
(This one is related to those mentioned above)

Old link: https://www.clir.org/hiddencollections/awards/
New link: https://www.clir.org/hiddencollections/funded-projects/

Old link: https://www.clir.org/hiddencollections/about-the-program/
New link: https://www.clir.org/hiddencollections/program-history/

**Mellon Fellows**

Old link: https://www.clir.org/fellowships/mellon/application-guidelines/
New link: https://www.clir.org/fellowships/mellon/applicantguidelines/

Old link: https://www.clir.org/fellowships/mellon/preservation/
New link: https://www.clir.org/fellowships/mellon/lc/

Old link: https://www.clir.org/fellowships/mellon/fellowship-recipients/
New link: https://www.clir.org/fellowships/mellon/fellowshiprecipients/

Old link: https://www.clir.org/fellowships/mellon/recipients/
New link: https://www.clir.org/fellowships/mellon/recipient-resources/

Old link: https://www.clir.org/fellowships/mellon/information-for-applicants/
New link: https://www.clir.org/fellowships/mellon/applicant-resources/

**Comment by waynegraham** [comment]
I've put these in, as well as a few others that were not listed here that were showing up in the 404 listings

**Comment by nkferraiolo** [comment]
THANK YOU!!!!!
