### ISSUE TITLE
"selected posts" on DLF front page showing duplicates again

### ISSUE THREAD

**Issue by nowviskie** [clirdlf/clir_theme#218]
Duplicate issue is back in the set of image links on the DLF home page, despite the fact that the post itself only has one category (our problem before) : 

![screen shot 2017-12-01 at 8 56 29 am](https://user-images.githubusercontent.com/92320/33485933-3bd65986-d676-11e7-9350-9e3653cec1c6.png)

**Comment by waynegraham** [comment]
The shortcode had `forum`; updated to `DLF Forum News`.
