### ISSUE TITLE
Scheduled posts aren't getting published.

### ISSUE THREAD

**Issue by bquon** [clirdlf/clir_theme#222]
Whenever I schedule a post, I check back a few minutes after the time it was supposed to go out, and find a red "Missed schedule" status. Have done this a few different times with the same result. 

![screen shot 2017-12-08 at 3 06 50 pm](https://user-images.githubusercontent.com/24256562/33783589-600009b4-dc2b-11e7-9eba-690b7405dc5c.png)

**Comment by waynegraham** [comment]
In doing a bit of research on this, it looks like an issue in WordPress (with how they implement cron jobs). 

> Someone has to visit the site before the event actually kicks off. So if you’ve scheduled something to happen hourly, but no one has visited your site in the last hour, then the event will never kick off.

I installed the [Scheduled Post Trigger](https://wordpress.org/plugins/scheduled-post-trigger/) plugin so hopefully this will go away. 

Please open a new ticket if you see this persist.
