### ISSUE TITLE
Bolded text issue

### ISSUE THREAD

**Issue by bquon** [clirdlf/clir_theme#223]
Bolded text isn't being reflected on published pages. See example:
https://wp.me/p8IA6d-4np

**Comment by waynegraham** [comment]
This returns a 404. Could you DM me the link where `<strong>` isn't rendering?

**Comment by bquon** [comment]
Whoops! 
https://dlf.wordpress.clir.org/fellow-reflection-nicola-andrews/
or 
https://www.diglib.org/dlf-strongly-opposes-fcc-proposal-weaken-net-neutrality-regulations/

**Comment by waynegraham** [comment]
This is a rendering issue in Chrome and the size of the regular size font being too close to the bold (see https://fonts.google.com/specimen/Montserrat). 

There are a few options:

1. Ignore it
2. Use a different font
3. Use Monserrat Light as the base font
4. use Monserrat Extra-Bold for the `<strong>` element
