### ISSUE TITLE
Featured Images

### ISSUE THREAD

**Issue by bquon** [clirdlf/clir_theme#224]
Is there a way to have "featured images" inserted at the top of each post that contains one in our archive? Like we've done manually here: https://dlf.wordpress.clir.org/dlfxdhsi-8-9-june-2018/ .

An example of a page where we haven't yet re-inserted the featured image: 
https://dlf.wordpress.clir.org/imls-grant-supports-21-hbcu-fellowships-to-dlf-forum/

Lots of our past posts are missing their images without this fix.

**Comment by waynegraham** [comment]
This is a setting in the theme (**Customize -> Blog -> Blog Single Post Page Options -> Display Featured Image**). 

I've turned this on, but there may be an edit needed in the `post-single.php` template.

**Comment by bquon** [comment]
Could you elaborate about the edit to the template? Featured images are still not being displayed. (example: https://dlf.wordpress.clir.org/dlf-events/2016forum/)

**Comment by waynegraham** [comment]
Featured Images are really for search engines and social displays (it comes from the older 'post thumbnail'). WordPress handles Posts slightly differently than Pages, but let me look at overriding this behavior in the templates.
