### ISSUE TITLE
titles and dates on posts

### ISSUE THREAD

**Issue by nowviskie** [clirdlf/clir_theme#228]
Somebody just linked to this _much older_ post on Twitter, and I notice that it lacks a title, date, and other metadata. The issue seems to be widespread and could cause some serious confusion. https://www.diglib.org/childcare-at-the-forum-2/

**Comment by waynegraham** [comment]
It doesn't appear as though any of the post metadata is displaying on the blog posts. I'll dig in to the settings and see what I can find.

**Comment by waynegraham** [comment]
Ok, so this is a weird one that I don't have enough information yet on yet to figure out a "good" fix for it. It appears as though if you click on the "Update" button, the author info appears. I need to do some more more investigation to see if I can't fix this without having to go in to every old post and click "Save" though.

**Comment by waynegraham** [comment]
I have a tested "solution" that walks through each post and clicks save (https://github.com/waynegraham/fix_diglib/blob/master/mechanize.rb). Since there are some things that can go wrong walking all 1,045 posts, I'll run this on a weekend when there are fewer users actively using the site.

**Comment by nowviskie** [comment]
Thanks so much, Wayne!

**Comment by waynegraham** [comment]
Dates and metadata (e.g. title, author, etc) are now on all posts (and verified).
