### ISSUE TITLE
Reports without Images

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/clir_theme#27]
We have a mix of Reports (http://staging.clir.org/pubs/reports/) where the more modern ones have covers for PDFs. However, we have publications that pre-date PDF 😲 We also have some that, for various reasons, the cover of the PDF was a separate thumbnail (I suspect from the days where PDFs were considered huge and it was a space saving not to include the cover). The result, then, is that we have reports with different size covers and some without a cover image. 

Is there a better way to display this kind of mixed content than the 3x grid?

**Comment by kimisgold** [comment]
I'm having trouble generating this mixed content on my install. The `[recent_publications count=""]` shortcode doesn't do anything, and I couldn't figure out the source. 

Looking at that page, I'm thinking there should be some way to bump up the visual interest of the text-only reports. Here's a mockup I did in the inspector:

<img width="823" alt="screen shot 2017-02-25 at 1 35 13 pm" src="https://cloud.githubusercontent.com/assets/606764/23333760/64a8a852-fb5f-11e6-9863-20cb10390986.png">

**Comment by waynegraham** [comment]
I should have noted the shortcode for that is in https://github.com/waynegraham/clir-widgets-bundle. Sorry about that, but I should be able to add this in pretty quickly.

**Comment by kimisgold** [comment]
What's the best way for me to activate this plugin on my local install? I pulled in the updated plugin, but the shortcode hasn't worked yet.

**Comment by waynegraham** [comment]
Hmm; is the plugin activated? Might need to check if https://github.com/waynegraham/clir-widgets-bundle/blob/master/lib/shortcodes.php#L280. I did make a change to that bit of code, but only to make the default show all (e.g. `[recent_publications]` vs `[recent_publications count=6]`).

**Comment by kimisgold** [comment]
I don't think plugin is activated, and I don't have the permissions to activate it as far as I can tell.
