### ISSUE TITLE
HTML versus PDF files

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#32]
In some of our older reports -- including annual reports -- there are html files that can possibly be deleted. For certain, it would be fine to keep just one pdf file of old CLIR Annual Reports in cases where both HTML and pdf are offered (i.e., 1999-2000; 2000-2001; 2001-2002). The earlier reports are only in HTML, so will probably have to stay as is... for now, anyway.

**Comment by waynegraham** [comment]
Do we have hard copies that could be digitized for earlier reports?

**Comment by Katsmi60** [comment]
Yes, we do.

Kathlin
