### ISSUE TITLE
CLIR Reports Page

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#33]
At present, report titles on the CLIR reports page are showing up with an image of the cover. Is this temporary—and will it revert to more of a list—or is the idea to also show the covers? While the covers add visual interest, it makes the whole list harder to see. Also, the order in which they appear is confusing—The State of Digital Preservation, and also Innovation, Collaboration and Models are both older publications, but they appear at the top.

**Comment by waynegraham** [comment]
This is related to https://github.com/waynegraham/clir-widgets-bundle/issues/1 and there is a ticket for some design love on what to do with publications that have no cover. This may turn in to more of a cover, title, and blub layout

**Comment by Katsmi60** [comment]
You don't think this will make for too long of a list, since we'll need to leave room for the image at each entry?

**Comment by waynegraham** [comment]
there would need to be some pagination; it would look more like the news page if this doesn't work out

**Comment by waynegraham** [comment]
I wrote several shortcodes to handle various iterations of this:

- `[recent_publications count=1]` - shows the last `n` recent publications. 
- `[publication title="Full Title of Publication"] - shows the publication of the matching title
- `[random_publication count=1]` - show `n` random publications

These shortcodes will allow a lot of flexibility in displaying (on various pages) these elements.
