### ISSUE TITLE
Navigation within pages

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#35]
At present, there does not appear to be a navigation menu visible when you go to a page (e.g., postdoctoral fellowships). You have to hover over the top menu bar to see a directory for the subpages of the site. This could be disorienting or confusing for someone; if you are reading a page, I think most people tend to look for cues on how to move to another page, and finding that guide might not be intuitive. I've asked Nikki if she thinks this could be a problem for users, and she thinks it would. It would be good to get input from other program staff. Is there a way to include navigation on each page?

**Comment by waynegraham** [comment]
Are we talking about child-level navigation here? I'm sure we can come up with something.

**Comment by waynegraham** [comment]
Moving to #39 (though this will be for all pages)
