### ISSUE TITLE
DHC: Adjustments on landing page 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#36]
The landing page is really pretty! Would it be possible to resize and adjust the following things?

- White navigation bar: when my browser window is small, the navigation bar shifts onto two lines, which makes it look really big. Is there a way to avoid that? 
- Main image: Can we make this smaller? Perhaps 1/2 or 2/3 of current height? It would be good to see a hint of text below it, so people know immediately they are in the right place. 
- DHC Fact sheet: Can we have the the fact sheet thumbnail surrounded by text, rather than having it hanging below. This would save some space on the page. 
- Lefthand nav bar: Can we make this a little bigger? currently it feels like there's some wasted space.
- Boxes below about section: I think we only need three boxes here: Applicant Resources, Recipient Info, and Registry. This would reduce the amount of space in this section and point the user to the three most important pages related to DHC. 
- Join our mailing list can be removed since people can subscribe at the bottom of the page (I presume this form at the bottom is for the DHC list, or is this to CLIR more generally?)--if it's not for DHC, they we can keep the join our mailing list text, although we don't need to give it it's own section. 
- Key Dates template looks good. I'll give you the text for the full timeline that we can include below. It's possible that it'll be more user-friendly to break this up into two sections.
- Eligibility: I like having the background for this section in another color, but we'll want to remove the background image that appears as you scroll, since this section will need to be very legible.

**Comment by waynegraham** [comment]
I'm breaking these in to separate tickets to track actions for all of these. Here are tickets in the same order presented here:

- https://github.com/clirdlf/clir_theme/issues/37
- https://github.com/clirdlf/clir_theme/issues/38
- Aligned the image to the left in the UI of WordPress
- https://github.com/clirdlf/clir_theme/issues/39
- https://github.com/clirdlf/clir_theme/issues/40
- Removed in the UI in WordPress
- https://github.com/clirdlf/clir_theme/issues/41
- https://github.com/clirdlf/clir_theme/issues/42
