### ISSUE TITLE
DHC Landing Page Image

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/clir_theme#38]
Can we make this smaller? Perhaps 1/2 or 2/3 of current height? It would be good to see a hint of text below it, so people know immediately they are in the right place.

**Comment by waynegraham** [comment]
Set the main section to 500px to mimic the landing page. 

```
.alchem-home-section-0 .magee-section {
    height: 500px !important;
    min-height: 500px !important;
}
```

**Comment by nkferraiolo** [comment]
I'm not sure I know where to put this code.
