### ISSUE TITLE
DHC Nav Bar Font Size

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/clir_theme#39]
Can we make this a little bigger? currently it feels like there's some wasted space.

**Comment by waynegraham** [comment]
Increase the navigation font size to 18px

**Comment by nkferraiolo** [comment]
I've done this, but it doesn't look particularly attractive. Do you have a model from elsewhere on the site for an attractive left-hand navigation bar? I imagine other programs will want to make use of this as well.

**Comment by waynegraham** [comment]
This will get handled in https://github.com/clirdlf/clir-widgets-bundle/issues/8
