### ISSUE TITLE
Resource Section

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/clir_theme#40]
Boxes below about section: I think we only need three boxes here: Applicant Resources, Recipient Info, and Registry. This would reduce the amount of space in this section and point the user to the three most important pages related to DHC.

**Comment by waynegraham** [comment]
@nkferraiolo The question I had on this section was which effect you wanted. The top row is an image to the resource and the second shows a flip on hover for more information. 

If you would like images, we need to find more appropriate images. If you like the flip card, we need to find appropriate logos (see http://fontawesome.io/icons/)

**Comment by nkferraiolo** [comment]
I actually think that the current effect is quite nice. If we replace the current images with images related to the DHC program (ideally from past grantees projects), and link them to the relevant pages, I think it will work well. 

Either the flip card, or a simple darkening of the box like you see now is fine. If we go with the darkened box upon hovering, we'll want to make sure the text becomes more visible, perhaps by having the color change to white.

**Comment by nkferraiolo** [comment]
I've been looking at this again, and I think I'm leaning towards the flipcard format. On the back, we should provide a brief explanation of what each page does. Is there a way I can plug in this additional text? I fear I may have accidentally deleted some of the code yesterday when playing around with it.

**Comment by waynegraham** [comment]
I'm going to close this for now; there's some more work to do to this section, but is greatly different than when this question was asked.
