### ISSUE TITLE
Key Dates

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/clir_theme#41]
Key Dates template looks good. I'll give you the text for the full timeline that we can include below. It's possible that it'll be more user-friendly to break this up into two sections.

**Comment by waynegraham** [comment]
These can be edited directly in the web interface.

**Comment by nkferraiolo** [comment]
I was able to find my login information for wordpress and have added in the content.

**Comment by waynegraham** [comment]
Can we close this one?

**Comment by nkferraiolo** [comment]
Yes.
