### ISSUE TITLE
Eligibility Background

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/clir_theme#42]
Eligibility: I like having the background for this section in another color, but we'll want to remove the background image that appears as you scroll, since this section will need to be very legible.

**Comment by waynegraham** [comment]
This can be done in the web interface for the page by editing the `[ms_section...]` shortcake.

**Comment by nkferraiolo** [comment]
Perhaps we could walk through how to do this together?

**Comment by waynegraham** [comment]
This is handled in this shortcode:

```
[ms_section background_color="" background_image="https://demo.mageewp.com/magee-shortcodes-demo/wp-content/uploads/sites/22/2016/04/al015.jpg" background_repeat="repeat" background_position="top left" background_parallax="yes" border_size="" border_color="" border_style="none" padding_top="30px" padding_bottom="30px" padding_left="10px" padding_right="10px" contents_in_container="yes" class="" id=""]
```

you're looking at the `background_image` component. 

I went ahead and removed these, as well as setting the `background_parallax` to `no`.
