### ISSUE TITLE
DHC: More spacing adjustments 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#43]
I've gone through the DHC landing page on the staging site and have started adding in content based on what we currently have on the website (edited down in some cases). While doing this, I seem to have messed up some of the spacing on the site. I can try adjusting this myself, but I didn't know if you were working off some sort of consistent standards or guidelines for how you're handling spacing and I didn't want to muck things up. Let me know if you'd like me to try to clean it up or if you'd prefer to do so yourself.

**Comment by waynegraham** [comment]
Go ahead and make all the content edits you want and then we can site down and work out spacing and flow issues

**Comment by nkferraiolo** [comment]
Great! I'm think I'm done making all of the major content adjustments. Anything else I'd change shouldn't affect spacing. Let me know when would be a good time to sit down and chat about this. I'll be around all today and next week and have very few meetings lined up for the time being.
