### ISSUE TITLE
DHC: Core values font 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#45]
The font of the core values list is different from the rest of the page. Is there a way to fix this?

**Comment by waynegraham** [comment]
It's the same font, just a different font-weight (it looks like). Docs on this are at https://demo.mageewp.com/magee-shortcodes-demo/list-shortcode/

I'll also take a look to see if there's something else going on...

**Comment by nkferraiolo** [comment]
It's possible, although it looks to me as if the main font on the page is a sans serif, and the font in the core values is a serif font.

**Comment by waynegraham** [comment]
I went in a different direction here. Can you take a look at https://staging.clir.org/hiddencollections/#core_values and comment?

**Comment by nkferraiolo** [comment]
I like it! It's a good opportunity to drop another image in!
