### ISSUE TITLE
DHC Applicant Resources Page 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#46]
Hi Wayne, 

I've started working on the content for the Applicant Resources page. After working on this a bit, I made some slight adjustments to the wireframe, which I've attached. The general idea is the same as what we had initially talked about. I've also created a google doc with text we can use for the page.

Thanks and let me know if you have any questions!

Nikki 

https://docs.google.com/document/d/1WamsCCOl0zU6hFKGWSNjOMiuBAGFnlz0twbC96raJrc/edit

[Updated wireframe DHC applicant resources.pdf](https://github.com/clirdlf/clir_theme/files/1252909/Updated.wireframe.DHC.applicant.resources.pdf)

**Comment by waynegraham** [comment]
I believe this has been blocked out...
