### ISSUE TITLE
DHC: Annotated staging page 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#47]
![hidden collections clir staging 2](https://user-images.githubusercontent.com/17573921/30221342-e4912092-9490-11e7-8d54-06504f086123.png)

Here are my annotations for small spacing adjustments.

**Comment by waynegraham** [comment]
Can you split this up in to smaller components for actions?

**Comment by nkferraiolo** [comment]
I have done so. See tickets #s: 61-69.
