### ISSUE TITLE
Update News Layout

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/clir_theme#49]
On News page (https://staging.clir.org/about/news/) is there a more space-efficient way of displaying news? Also, it looks like this page has brought in items that aren’t from the news section (for example, it lists CLIR Issues releases). Can we discuss this?

**Comment by waynegraham** [comment]
I made this in to a grid (which will look better with images). This is the "posts" archive which shows everything and we can have different page filters for different sections. We may need to move the main page if there is "News" that isn't news...

**Comment by waynegraham** [comment]
@Katsmi60 How does this look?

**Comment by Katsmi60** [comment]
It has a nice, clean look. I'm taking a gander at other orgs sites to see how they are handling news—and how much older news is viewable. Two immediate things to note: the page heading says CLIR Issues and it should say News. Also, how are these items fed into the news page? Normally, I would only include news releases, and not, for example, the release of CLIR Issues.

**Comment by waynegraham** [comment]
This view has all the "post" data types (things that have a temporal aspect to them). We can create a page with just specific post types (e.g. 'news'), but this is a nice place just to have everything as these resources are typically read by third party readers (e.g. it's our RSS/Atom feed).

**Comment by Katsmi60** [comment]
On the question of whether or not to include CLIR Issues releases as "news," I think I'd rather not have it included, in part because CLIR Issues almost always includes some news that repeats what we've already announced at other times.

**Comment by Katsmi60** [comment]
On news page, change heading from CLIR Issues to News
