### ISSUE TITLE
Landing Page Slider

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/clir_theme#53]
Update the landing page slider to include the story of why CLIR exists.

**Comment by waynegraham** [comment]
@Katsmi60 This may be a useful resource for this: https://uxplanet.org/best-practices-for-hero-images-eeb234b664d6

**Comment by waynegraham** [comment]
Can this one get closed @Katsmi60?

**Comment by Katsmi60** [comment]
Yes, this can be closed.
