### ISSUE TITLE
DHC: Side nav bar 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#61]
The only items that should appear in the side navigation bar are: 
**Program History
Applicant Resources
Recipient Information
Registry**

- For Program History, you can pull content from the current "About the Program" page
- Applicant Resources still needs to be created. I shared a wireframe and google doc with text for the page with you. 
- For Recipient Information, you can pull content from the current "For Recipients" page

All other DHC pages should not show up on the new site.

**Comment by waynegraham** [comment]
Do you want to take a stab at updating this @nkferraiolo?

**Comment by nkferraiolo** [comment]
I don't know whether to update the links with links to the pages on the staging site or CLIR's current site. I don't want the URLs to break when we go live. Also some of the URLs will changes, because we've changed the names of some of these pages. 

I also don't know how to hide the unnecessary pages from the left-hand nav bar.

**Comment by waynegraham** [comment]
Will be refactored in to https://github.com/clirdlf/clir-widgets-bundle/issues/8
