### ISSUE TITLE
DHC: Core Values image 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#63]
Please add in the new image for the core values section. 

![4_berkeley](https://user-images.githubusercontent.com/17573921/30716061-9dcf685c-9ee6-11e7-921c-b1575056209d.jpg)

**Comment by nkferraiolo** [comment]
I will add this to the media library, then Wayne will add it to the site.

**Comment by waynegraham** [comment]
I'll show you how to do this
