### ISSUE TITLE
DHC: Add images to 3 boxes at bottom of page 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#67]
Applicant Resources = Washington University
Recipient Information = Atlanta University Center
Registry = Museum of Flight 

![5_themuseumofflight](https://user-images.githubusercontent.com/17573921/30716282-79536e1e-9ee7-11e7-8dbf-eeaad1f77755.jpg)
![6_atlantauniversitycenter](https://user-images.githubusercontent.com/17573921/30716284-795e2c32-9ee7-11e7-80b7-91f2f49064e1.jpg)
![7_washingtonuniversityinstlouis](https://user-images.githubusercontent.com/17573921/30716283-79554144-9ee7-11e7-8ca9-2c8aa02f1cd1.jpg)

**Comment by waynegraham** [comment]
Have these been uploaded in to WordPress? If so, get the image URL for them and add them to the shortcode for those boxes. 

```
[ms_image_banner image="https://demo.mageewp.com/magee-shortcodes-demo/wp-content/uploads/sites/22/2016/04/portfolio_02-300x225.jpg" link="" target="_blank" horizontal_align="center" vertical_align="top" zoom_effect="in" class="" id=""]
```

The `image` part should look something like 

```
/wp-content/2017/10/some-image-name.jpg
```

The only other thing to mention is that you may need to edit the image (in WordPress) to resize it to 320x320.

**Comment by nkferraiolo** [comment]
I'm not sure I know how to do that. Perhaps we could go over it at our meeting tomorrow or on Tuesday?

**Comment by waynegraham** [comment]
I've added these, but the Recipient image (https://staging.clir.org/hiddencollections/#additional_information) is too small. Any chance you have a larger image (around 470x470)?
