### ISSUE TITLE
DHC: Additional images to add to Eligibility and Award Terms sections. 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#73]
Here are two images to break up the walls of text. Perhaps put the Duke image in the eligibility section and the UCLA image in the Award Terms section.

![duke image](https://user-images.githubusercontent.com/17573921/30717689-bd0fc716-9eeb-11e7-87ae-6cc66fb7ad31.jpg)
![ucla clark](https://user-images.githubusercontent.com/17573921/30717707-c4a039b6-9eeb-11e7-9ba4-88f15b223285.jpg)

**Comment by waynegraham** [comment]
Do you really want these images behind the text? I think because of the detail the images will distract from the readability of those sections.

**Comment by nkferraiolo** [comment]
Nope! I wasn't thinking that they would go behind the text, but rather next to it. I thought it might be nice to wrap the text around it so there's some color on that part of the page. If you think it's overkill we can use it elsewhere. I just mostly want to get an image of an audio format on the landing page so people know that's a format we fund!
