### ISSUE TITLE
Photos and blurbs for News and Program Spotlight

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#81]
I've written three news blurbs and three program spotlights, and I have put images in the media library. Note that many of these are placeholders... the purpose for the moment is to give a fairly good idea of what the home page will look like and what type of content will be under each area.
Let me know if you have any trouble opening this attachment.

[6 blurbs.docx](https://github.com/clirdlf/clir_theme/files/1341710/6.blurbs.docx)

**Comment by waynegraham** [comment]
We need larger images, but these will work for now

**Comment by waynegraham** [comment]
I've put in holder images with the dimension for this section (350x233). Could you upload a few images (even placeholders) for these without any compression?

**Comment by waynegraham** [comment]
I believe we've closed this; let me know if there is additional work that needs to be done.
