### ISSUE TITLE
Publications to feature on home page

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#82]
These three would be good for the first month or so:

https://www.clir.org/pubs/reports/pub174
https://www.clir.org/pubs/reports/pub171/pub171abst
https://www.clir.org/pubs/reports/pub164

You have a way of bringing in the cover images automatically, right? No need to provide?

**Comment by waynegraham** [comment]
There is a shortcode to manage these; 

```
[recent_publications count="1"]

[publication title="ARSC Guide to Audio Preservation"]

[publication title="The Open Data Imperative: How the Cultural Heritage Community Can Address the Federal Mandate"]
```

There is an additional shortcode

```
[random_publication count="1"]
```

That allows for a random publication to be displayed when the page is rendered.
