### ISSUE TITLE
PostDoc Image Slider

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/clir_theme#92]
We'll need images for the main page slider for the PostDoc program (between 1 and 3 with "call to action" text).

**Comment by Katsmi60** [comment]
Wayne, I think that for the postdoc program page, we'd been thinking about no slider action (at least for the launch) -- instead we'd have just one non sliding image. That image is currently in the media gallery -- 
![screen shot 2017-10-06 at 1 23 19 pm](https://user-images.githubusercontent.com/25488670/31290220-a2b79b14-aa99-11e7-85f0-ae6e18a6296a.png)
