### ISSUE TITLE
Cover for ARSC Guide should be visible on landing page, publication area

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#94]

**Comment by waynegraham** [comment]
This is the cover that is on the PDF that's uploaded. I noticed that for a lot of reports, the covers were different than what were on the PDFs (until kind of recently). I can override this, but fear that if we have to regenerate images for the PDFs, we'll loose this. Is there a way to get a PDF of this with the correct cover?

**Comment by Katsmi60** [comment]
Hi, Wayne,

I think we chose not to include the cover in the pdf download because it would have added size to an already large file—unusually large for anything we publish, because of the number of graphics. So this is an oddball.

Kathlin

**Comment by waynegraham** [comment]
This PDF (by today's terms) isn't that big. Any chance you could generate a PDF with the correct cover?
