### ISSUE TITLE
Type size for publications titles on landing page

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#95]
Can the font size be reduced for the publication titles on the landing page? Also, can text be in black, rather than blue, to be consistent with other items on landing page? People will still try to click, I think, and we can make both image and text link to abstract, right?

**Comment by waynegraham** [comment]
We can play with the size of header, but the blue color is from the fact that it's a hyperlink to hint to the user that this is an object that can be clicked on (and not just for decoration).

I made the covers a bit larger, so having the titles under the cover may be a bit redundant.

Thoughts?

**Comment by Katsmi60** [comment]
Home page is looking much better. Thanks!

I don’t think we need titles underneath the publications now that they are larger. Also, I’ve removed the Lorum ipsum text under publications and program spotlight a couple of times, but now it’s back. Also had removed “Satement About CLIR” header at top, which I don’t think is necessary. Is there some reason this text keeps reappearing?

Thanks,

Kathlin

**Comment by waynegraham** [comment]
Moving to https://github.com/clirdlf/clir-widgets-bundle/issues/11
