### ISSUE TITLE
Add Text for Program Page Sliders

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/clir_theme#96]
Each program should have text on the slider with a "call to action" and their name.

**Comment by waynegraham** [comment]
Initial text is added on all program-specific sliders. There are two new custom formats:

- `Program-title` sets the font to Roboto Slab 48px and color of `#ffffff` (white)
- `Program Subtitle` sets the font to Roboto Slab, 22px, and color `#ffffff` (white)

Individual slides were made with different colors, but we can use these as a beginning point for each of the programs.

**Comment by Katsmi60** [comment]
Wayne, on the CIO’s page, the image is not displaying and I’m getting a message in orange (see enclosed screen shot)

Kathlin
